apiVersion: v1
kind: Service
metadata:
  name: devsecops-node-service
spec:
  type: NodePort
  selector:
    app: devsecops-node-app
  ports:
    - port: 80
      targetPort: 5006
      nodePort: 30007
